server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://gz-cdb-975vpfib.sql.tencentcdb.com:57620/auctiondb?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 175176as
    servlet:
      multipart:
        max-file-size: 100MB
        max-request-size: 100MB

pagehelper:
  helper-dialect: mysql
  reasonable: true

file:
  stacticAccessPath: '/pic/**'
  uploadFileFolder: 'd:/duagram/'

